<?php

namespace Dyd\Changeset;

use Dyd\Changeset\ChangesetEntry;

/**
 * Test class for ChangesetEntry.
 * Generated by PHPUnit on 2011-09-23 at 22:49:59.
 */
class ChangesetEntryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Test creation of Changeset
     */
    public function testCreateChangeset()
    {
        $fileContent = <<< EOF
SELECT 1;
--//@UNDO
DELETE 1;
EOF;

        $filesystemMock = $this->getFilesystemMock($fileContent);

        $actualChangeset = new ChangesetEntry('TestChangeset.sql', $filesystemMock);

        $this->assertEquals('TestChangeset.sql', $actualChangeset->getName());
        $this->assertEquals('SELECT 1;', $actualChangeset->getChangeSql());
        $this->assertEquals('DELETE 1;', $actualChangeset->getRollbackSql());
    }

    /**
     * Test creation of Changeset with missing UNDO-token
     */
    public function testCreateChangesetWithMissingUndoToken()
    {
        $fileContent = <<< EOF
SELECT 1;
DELETE 1;
EOF;

        $filesystemMock = $this->getFilesystemMock($fileContent);

        try {
            new ChangesetEntry('TestChangeset.sql', $filesystemMock);
        } catch (\Exception $e) {
            $this->assertEquals(
                "File 'TestChangeset.sql' has no UNDO-token.",
                $e->getMessage(),
                'Wrong file format should cause appropriate exception.'
            );
            return;
        }

        $this->fail('File with wrong format should throw exception.');

    }

    /**
     * Test creation of Changeset with empty file
     */
    public function testCreateChangesetWithEmptyFile()
    {
        $filesystemMock = $this->getFilesystemMock('');

        try {
            new ChangesetEntry('TestChangeset.sql', $filesystemMock);
        } catch (\Exception $e) {
            $this->assertEquals(
                'File is empty.',
                $e->getMessage(),
                'Empty file should cause appropriate exception.'
            );
            return;
        }

        $this->fail('Empty file should throw exception.');
    }

    /**
     * Test creation of Changeset that does not contain SQL
     */
    public function testCreateChangesetWithoutChangeSql()
    {
        $fileContent = <<< EOF
--//@UNDO
DELETE FROM foo;
EOF;

        $filesystemMock = $this->getFilesystemMock($fileContent);

        try {
            new ChangesetEntry('TestChangeset.sql', $filesystemMock);
        } catch (\Exception $e) {
            $this->assertEquals(
                "File 'TestChangeset.sql' does not contain change-SQL.",
                $e->getMessage(),
                'File without SQL should cause appropriate exception.'
            );
            return;
        }

        $this->fail('File without SQL should throw exception.');
    }

    /**
     * Test creation of Changeset that does not contain SQL
     */
    public function testCreateChangesetWithoutRollbackSql()
    {
        $fileContent = <<< EOF
ALTER TABLE foo;
--//@UNDO
EOF;

        $filesystemMock = $this->getFilesystemMock($fileContent);

        try {
            new ChangesetEntry('TestChangeset.sql', $filesystemMock);
        } catch (\Exception $e) {
            $this->assertEquals(
                "File 'TestChangeset.sql' does not contain rollback-SQL.",
                $e->getMessage(),
                'File without SQL should cause appropriate exception.'
            );
            return;
        }

        $this->fail('File without SQL should throw exception.');
    }

    /**
     * Test creation of Changeset that does not contain SQL
     */
    public function testTrimmingOfSqlString()
    {
        $fileContent = <<< EOF

 SELECT 1;

--//@UNDO

 DELETE 1;

EOF;

        $filesystemMock = $this->getFilesystemMock($fileContent);

        $actualChangeset = new ChangesetEntry('TestChangeset.sql', $filesystemMock);

        $this->assertEquals('TestChangeset.sql', $actualChangeset->getName());
        $this->assertEquals('SELECT 1;', $actualChangeset->getChangeSql());
        $this->assertEquals('DELETE 1;', $actualChangeset->getRollbackSql());
    }

    /**
     * Sets up mock of filesystem, defines filecontent as well
     *
     * @param string $fileContent
     * @return \Dyd\Util\Filesystem $mockedFilesystem
     */
    private function getFilesystemMock($fileContent)
    {
        $filesystem = $this->getMockBuilder('\Dyd\Util\Filesystem')
            ->disableOriginalConstructor()
            ->getMock();

        $filesystem
            ->expects($this->any())
            ->method('readFromFile')
            ->will($this->returnValue($fileContent));

        return $filesystem;
    }
}

