<?php

namespace Dyd\Util\Database\Driver;

/**
 * Test class for SqliteDatabase.
 * Generated by PHPUnit on 2011-11-05 at 13:43:41.
 */
class SqliteTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SqliteDatabase
     */
    protected $database;

//    /**
//     * Sets up the fixture, for example, opens a network connection.
//     * This method is called before a test is executed.
//     */
//    protected function setUp() {
//        $pdo = new \PDO('sqlite:memory');
//        $this->database = new SqliteDatabase($pdo);
//    }
//
//    public function testCreateChangelogTable()
//    {
//        $this->database->createChangelogTable();
//
//        $statement = $this->pdo->query("SELECT name FROM sqlite_master WHERE name='dyd_changelog';");
//    }
//
//    public function testHasChangelogTable()
//    {
//
//    }
//
//    /**
//     * @covers {className}::{origMethodName}
//     * @todo Implement testRetrieveChangelogs().
//     */
//    public function testRetrieveChangelogs() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers {className}::{origMethodName}
//     * @todo Implement testRetrieveChangelogByName().
//     */
//    public function testRetrieveChangelogByName() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers {className}::{origMethodName}
//     * @todo Implement testExecQuery().
//     */
//    public function testExecQuery() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers {className}::{origMethodName}
//     * @todo Implement testWriteChangelog().
//     */
//    public function testWriteChangelog() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers {className}::{origMethodName}
//     * @todo Implement testDeleteChangelog().
//     */
//    public function testDeleteChangelog() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

}